codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "70...90"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "tests/**"
  - "test_*.py"
  - "h2p_parser/utils/**"
  - "h2p_parser/data/**"
  - "**/__main__.py"
  - "**/__init__.py"
