name: CodeCov Coverage

on:
  push:
    branches: [ main ]
    paths:
      - '*.py'
      - 'requirements.txt'
      - 'h2p_parser/**'
      - 'tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - '*.py'
      - 'requirements.txt'
      - 'h2p_parser/**'
      - 'tests/**'

jobs:
  run:
    name: CodeCov Coverage
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Generate Report
      run: |
        python -m coverage run -m unittest discover -s tests -p 'test_*.py' -t tests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        flags: unittests
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true