name: Python Lint Check

on:
  push:
    branches: [ main ]
    paths:
      - 'h2p_parser/**'
      - 'tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'h2p_parser/**'
      - 'tests/**'

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v1
      - uses: marian-code/python-lint-annotate@v3
